# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackernews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('num_comments', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-date', '-num_comments'],
            },
        ),
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('num_comments', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-date', '-num_comments'],
            },
        ),
        migrations.CreateModel(
            name='Slashdot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('num_comments', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-date', '-num_comments'],
            },
        ),
    ]
