# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
