# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_reddit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddit',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
