# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_reddit_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackernews',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hackernews',
            name='star',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slashdot',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='slashdot',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
