# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20171122_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddit',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
