# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20171128_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('star', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
