# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_chan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chan',
            options={'ordering': ['-date', '-num_comments']},
        ),
        migrations.AddField(
            model_name='chan',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
