# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20171128_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chan',
            name='summary',
        ),
    ]
