# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_remove_chan_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chan',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
