# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_chan_md5'),
    ]

    operations = [
        migrations.AddField(
            model_name='chan',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
